name: Trigger Tests Manually
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      DINOSAUR:
        description: 'Creature that is expected to be dinosaur:'
        # Default value if no value is explicitly provided
        default: achillobator
        # Input has to be provided for the workflow to run
        required: true
      NOT_DINOSAUR:
        description: 'Creature that is not a dinosaur:'
        # Default value if no value is explicitly provided
        default: dog
        # Input has to be provided for the workflow to run
        required: true
      tags:
        description: 'Tags for tests to run. Use "*" to run all'
        # Default value if no value is explicitly provided
        default: dinosaur
        # Input has to be provided for the workflow to run
        required: true
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Robot Framework Tests
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:${{ github.event.inputs.DINOSAUR }} --variable NOT_DINOSAUR:${{ github.event.inputs.NOT_DINOSAUR }} --include ${{ github.event.inputs.tags }}" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
